### ISSUE TITLE
iOS can't operate the app with Voice Over 

### ISSUE THREAD

**Issue by akatsudon** [viezel/NappDrawer#102]
Running the demo that comes with the module in iOS 7 with Voice Over enabled, elements and controls won't receive focus. Voice Over will only focus to the iOS 7 Status bar and read out the current time, battery level, device name and network state.

However, it works perfectly fine in Android with the TalkBack. Everything focus and read out fine. 

Would you have some hint on why it wouldn't work on iOS?

**Comment by mano-mykingdom** [comment]
I'm facing the same issue, Is there any fix or work around?

**Comment by mano-mykingdom** [comment]
I got a solution, 

1. setting the accessibilityHidden property of left and center window to false (to be set on the open event of drawer, setting it before open event didn't work) 

$.drawer.centerWindow.accessibilityHidden = false;
$.drawer.leftWindow.accessibilityHidden = false;

Also setting accessibilityLabel property of drawer instance to some string makes voice over works. 

$.drawer.accessibilityLabel = Ti.App.name;

@viezel - from this, do you get any idea to fix this within the module itself. You may also have a look at  this issue https://github.com/mutualmobile/MMDrawerController/pull/276 which may related to this I guess.

**Comment by mano-mykingdom** [comment]
I have one more problem now, when I open the left window the voice over doesn't focus the first item there automatically. Any tips?

**Comment by dylan-oxide** [comment]
I have updated the iOS code to add support for tapping on elements in VoiceOver. It doesn't support swiping left and right, but it is a start.
