### ISSUE TITLE
setCenterWindow/setLeftWindow/setRightWindow crashes app on SDK 3.4.0.GA

### ISSUE THREAD

**Issue by skoften** [viezel/NappDrawer#120]
MainWindow stops working after one of these functions is called (left, center or right), and crashes.

SDK 3.4.0.GA, iOS 8.1

Code used:

// args
var args = arguments[0] || {};

// menu module
var NappDrawerModule = require('dk.napp.drawer');

// create main app window based on slide menu addon
var emptyWin = Ti.UI.createWindow({
    backgroundColor: 'red',
    statusBarStyle: Ti.UI.iPhone.StatusBar.LIGHT_CONTENT
});

var leftWin = Ti.UI.createWindow({
    backgroundColor: 'green',
    statusBarStyle: Ti.UI.iPhone.StatusBar.LIGHT_CONTENT
});
var rightWin = Ti.UI.createWindow({
    backgroundColor: 'blue',
    statusBarStyle: Ti.UI.iPhone.StatusBar.LIGHT_CONTENT
});

// main app window
var mainAppWindow = NappDrawerModule.createDrawer({
    centerWindow: emptyWin, 
    leftWindow: leftWin,
    rightWindow: rightWin,
    closeDrawerGestureMode: NappDrawerModule.CLOSE_MODE_ALL,
    openDrawerGestureMode: NappDrawerModule.OPEN_MODE_ALL,
    leftDrawerWidth: 180,
    rightDrawerWidth: 220,
    statusBarStyle: NappDrawerModule.STATUSBAR_WHITE,
    orientationModes: [Ti.UI.PORTRAIT, Ti.UI.UPSIDE_PORTRAIT]
});

mainAppWindow.setShowShadow(false);

// open it
mainAppWindow.open({
    opacity: 1,
    duration: 1
});

var leftWindow = Ti.UI.createWindow({
    backgroundColor: 'white'
});

// set window center

setTimeout(function() {
    mainAppWindow.setCenterWindow(leftWindow);
},3000);

**Comment by hansemannn** [comment]
This should be fixed in ios-2.1.1, thx!
