### ISSUE TITLE
How to hide actionbar in android 

### ISSUE THREAD

**Issue by wannaporn** [viezel/NappDrawer#131]
I want to hide actionbar on centerview. I used Titanium SDK 3.4.0. GA.
Thank you.

![screenshot_2014-12-12-11-08-34](https://cloud.githubusercontent.com/assets/6166935/5407065/1b4a38fe-81f1-11e4-8329-977e0378c4f4.png)

![screenshot_2014-12-12-11-08-18](https://cloud.githubusercontent.com/assets/6166935/5407063/1b40e8d0-81f1-11e4-808f-dd7a47457b26.png)

![screenshot_2014-12-12-11-08-29](https://cloud.githubusercontent.com/assets/6166935/5407064/1b41b990-81f1-11e4-9897-6ec1adb77f8c.png)

**Comment by viezel** [comment]
use Q&A
