### ISSUE TITLE
[Android] navBarHidden ignored in Android 2.3.X / API 10 

### ISSUE THREAD

**Issue by skoften** [viezel/NappDrawer#133]
The navigation/actionbar can't be hidden on Android 2.3.X. On higher settings navBarHidden to true works though.

With normal winwdows I solved it by hiding the actionbar activity after the window has opened, but this doesn't works with the nappdrawer window object:

```
// WORKS for API 10
$.loginWindow.addEventListener("open", function() {
     $.loginWindow.activity.actionBar.hide();
});
```

```
// Doesn't work with nappdrawer 
var mainAppWindow = NappDrawerModule.createDrawer({
	navBarHidden: true,	
    fullscreen:false, 
    leftWindow: leftWindow,
    exitOnClose: true,
    centerWindow: centerWindow,
    fading: 0.2, // 0-1
    parallaxAmount: 0.2, //0-1
    shadowWidth:"15dp", 
	leftDrawerWidth: Alloy.Globals.isTablet ? '270dp' : '200dp',
	rightDrawerWidth: Alloy.Globals.isTablet ? '270dp' : '200dp',
    animationMode: NappDrawerModule.ANIMATION_NONE,
    closeDrawerGestureMode: NappDrawerModule.CLOSE_MODE_MARGIN,
    openDrawerGestureMode: NappDrawerModule.OPEN_MODE_ALL
});

// hide navbar
mainAppWindow.addEventListener("open", function() {
     mainAppWindow.activity.actionBar.hide();
});
```
Result: 

![error](https://cloud.githubusercontent.com/assets/1286410/5535730/0f305408-8a85-11e4-8f57-31f2a2e2143a.jpg)

So the question is: how can I hide the navbar/actionbar for the main window of nappdrawer?

Thanks.

**Comment by viezel** [comment]
have you tried:

     drawer.getActivity();

as I do here: https://github.com/viezel/NappDrawer/blob/master/android/example/app.js#L223

**Comment by viezel** [comment]
but you could also try the theme property:
http://docs.appcelerator.com/titanium/3.0/#!/api/Titanium.UI.Window-property-theme

**Comment by skoften** [comment]
.getActivity() works, thanks!
