### ISSUE TITLE
in iOS setCenterWindow(window) on a window which is already in the center causes the app to crash (looks like bug was introduced in 1.2.0)

### ISSUE THREAD

**Issue by fahad86** [viezel/NappDrawer#139]
Tested with Titanium SDK 3.5.0

**Comment by fahad86** [comment]
Tested with Titanium SDK 3.5.0

**Comment by fahad86** [comment]
A workaround would be to manually check if the current center window is the same as the one being set to and skip if same:
e.g.)
      if(SliderMenuWindow.centerWindow != myFirstPage){
        SliderMenuWindow.setCenterWindow(myFirstPage);  
      }

**Comment by long** [comment]
I ran into this issue 99% of the time when calling setCenterWindow(new_window).  Not sure if that 1% was a fluke.

I tracked it down to the MMDrawerController submodule (MMDrawerController/MMDrawerController.m) where 

    if(oldCenterViewController){
        [oldCenterViewController willMoveToParentViewController:nil];
        if(animated == NO){
            [oldCenterViewController beginAppearanceTransition:NO animated:NO];
        }
        [oldCenterViewController removeFromParentViewController];
        [oldCenterViewController.view removeFromSuperview];
        if(animated == NO){
            [oldCenterViewController endAppearanceTransition];
        }
    }

should have the `removeFromSuperview` called before `removeFromParentViewController`

    if(oldCenterViewController){
        [oldCenterViewController willMoveToParentViewController:nil];
        if(animated == NO){
            [oldCenterViewController beginAppearanceTransition:NO animated:NO];
        }
        [oldCenterViewController.view removeFromSuperview];
        if(animated == NO){
            [oldCenterViewController endAppearanceTransition];
        }
        [oldCenterViewController removeFromParentViewController];
    }

Rebuilding the NappDrawer iOS module without any additional changes now works without crashing my app.

**Comment by caspahouzer** [comment]
Then could you do a PR on MMDrawerController?

**Comment by long** [comment]
In the process of setting up the PR on MMDrawerController

**Comment by long** [comment]
Created the PR https://github.com/mutualmobile/MMDrawerController/pull/324

**Comment by caspahouzer** [comment]
:+1:
