### ISSUE TITLE
[enhancement] darken up the center

### ISSUE THREAD

**Issue by caspahouzer** [viezel/NappDrawer#141]
could you provide a parameter false/true to darken up the center view on opening left or right window?

Of course, this could be implemented in my sourcecode on windowDidOpen and windowDidClose.
But wouldn't it be elegant to have an fading black overlay on the center window?

Just an idea

**Comment by guiled** [comment]
I wrote #91 that is the same demand... I think there will be no enhancement here

**Comment by mpociot** [comment]
I also think that this is too application specific, to enable this in the main module (cross platform)

**Comment by caspahouzer** [comment]
ok

**Comment by guiled** [comment]
I may be too application specific but it is impossible to make a smooth fade to black without writing it in native code.
And what about the fading effect for the left and right window? Are they application specific.

Even though I wrote there won't be any enhancement, I wish I have this feature for an app where users can be disturbed with the fact that center window is not reacting when left window is shown...

**Comment by caspahouzer** [comment]
I tried it out. The problem is, that I don't know, how far the left or right window is opened to set the opacity level. I can only react on opened and closed to overly the center. Of course, I'm fading in, but on closing, the center is overlaid until the sidebar is completely hidden.

If I have a percentage indicator of the distance how open the sidebar is, then it would be no problem to create an own solution.
