### ISSUE TITLE
set new leftDrawerWidth animated

### ISSUE THREAD

**Issue by caspahouzer** [viezel/NappDrawer#147]
On iPad, I have a search bar in my left navigation. On focus I want to expand the left navigation width. This works as expected, but I want it smooth. Is that possible?

**Comment by mpociot** [comment]
Hey,

I implemented this a while back:

```javascript
mainWindow.setLeftDrawerWidth({
    width: 160,
    animated: true
});
```

**Comment by caspahouzer** [comment]
Just have to read the docs... :camel:
