### ISSUE TITLE
Not compatible with Titanium SDK 4.0.0

### ISSUE THREAD

**Issue by deckameron** [viezel/NappDrawer#154]
I tested it on Android 5.1 and it didn't work.

**Comment by Anatidae-Project** [comment]
Nope. The ti.drawerlayout module does and is closer to android design guides. Still, it will be nice to get this fixed.

**Comment by Geek-Fish** [comment]
Works fine on iOS - This is just an Android issue.

**Comment by adamkearsley** [comment]
Its the SDK thats causing the error, running 3.5.1GA works ok on Android 5.
The issue has been found and can be resolved if the owner of this repo makes the changes mentioned in the comments here:
https://github.com/viezel/NappDrawer/issues/135

**Comment by mpociot** [comment]
Or if you fork the repo and make a pull request :+1:

**Comment by adamkearsley** [comment]
Done
https://github.com/viezel/NappDrawer/pull/156
