### ISSUE TITLE
Create SDK 4.1.0 release

### ISSUE THREAD

**Issue by beaurushton** [viezel/NappDrawer#175]
Hi I see a pull request was merged to fix some issues with 4.1.0.  Could we get a release for that?

**Comment by PietroGranati** [comment]
Same question for me!

**Comment by guiled** [comment]
:+1:

**Comment by ifavo** [comment]
:+1: same for me, would be great if somebody could compile it – my try on it sadly failed :)

**Comment by ifavo** [comment]
Thanks a lot, mano! :+1:
