### ISSUE TITLE
'open' event listener only responds to Android

### ISSUE THREAD

**Issue by gabeaguirre** [viezel/NappDrawer#176]
If you do not instantiate a webview with the 'open' event listener and try to set the center window, you lose context for web drop downs and other behavior. However, on iOS this 'open' event is never fired.

**Comment by davide-quix** [comment]
I'm experiencing the same problem. I cannot see the dropdown list of HTML select element in webview.
Is there a way to solve this issue?

**Comment by gabeaguirre** [comment]
If you are on Android, before you instantiate your webview or add it to your center window, put those events inside the 'open' event that is fired. You have to wait until the drawer is fully opened. Slows stuff down on start but its worth it for full functionality.

**Comment by hansemannn** [comment]
This should not be an issue for the iOS 2.0.0+ version anymore. See https://github.com/viezel/NappDrawer/issues/178 for details.

**Comment by quix-portal** [comment]
I'm trying to solve this issue in Android webview but the dropdown list is never shown, even if the webview is instantiated and added to the center window inside drawer 'open' event. Does anyone know how to solve this? Is this already a know issue? I'm currently testing on Android 8.
