### ISSUE TITLE
Add 'opening' and 'closing' events

### ISSUE THREAD

**Issue by mawarnes** [viezel/NappDrawer#178]
Hi, first of all great module,so thanks
Secondly would it be possible/how would I to add 'opening' and 'closing' events which fire at the start of a gesture or click so that I can toggle the status bar.
What I would like to do is switch off the status bar at the start of a pan gesture rather than the end, I'm probably missing something very obvious but I'm not great at obj-c...I've looked into the MMDrawerController code but can't see a starting point. Would anyone perhaps have any helpful suggestions on whether this is even possible?
Many thanks?

**Comment by hansemannn** [comment]
There are events for opening / closing the drawer als well as focus/blur events for the center-window. See the updated [README](https://github.com/viezel/NappDrawer/blob/master/ios/README.md) for details.
