### ISSUE TITLE
Android optionMenus no longer working on 1.1.6 + SDK 4.1

### ISSUE THREAD

**Issue by ifavo** [viezel/NappDrawer#179]
Hey everyone!

I am having trouble with the optionsMenu since updating to 1.1.6 and SDK 4.1

With the version 1.1.4 and SDK 3.5 everything was working fine but now suddenly the menu no longer appears. Using the identical code on windows created myself still works fine which indicates that there is a change in the Drawer module. Browsing thru some of the commits I couldn't find anything obvious change regarding this.

Was there any change or is there a known bug regarding the Android optionMenus?

Cheers,
 Mario

**Comment by pedrohatanasio** [comment]
Same problem here.

**Comment by Anatidae-Project** [comment]
Might be related to: 
https://github.com/viezel/NappDrawer/issues/180

As the homeAsUp icon also uses the Android menu as it's listener.

I'm not sure this repo is maintained on Android though.

**Comment by rwuttke** [comment]
I have the same problem, I had a specific icon for the .icon property, and had two menu items, nothing is appearing, when they previously did (ie 3.5.1.GA SDK, 1.1.4)

Call invalidateOptionsMenu and the onCreateOptionsMenu is not called.

Agree with Anatidae-Project about the relationship.

**Comment by rwuttke** [comment]
Question, have you guys tried using the

hamburgerIcon : true
and optionally
hamburgerIconColor : <colour>

I did this and it started working.

I have my menus, and everything seems to be working.
