### ISSUE TITLE
Drawer crashes

### ISSUE THREAD

**Issue by abhiit61** [viezel/NappDrawer#190]
Hi,

I have added the drawer in my app using your sample example for android. When I launch the application it throws following error

 TiExceptionHandler: (main) [0,72] - Message: Uncaught ReferenceError: doClick is not defined
[ERROR] :  TiExceptionHandler: (main) [0,72] - Source:     doClick ? $.addListener($.__views.label, "click", doClick) : __defers["$._

Any idea how to solve this?

**Comment by hansemannn** [comment]
This should not be an issue anymore.
