### ISSUE TITLE
Misleading link in the documentation of the Android version

### ISSUE THREAD

**Issue by asiby** [viezel/NappDrawer#196]
Hello

In the Android version, there this like ...

> For Alloy projects, use the [nl.fokkezb.drawer](https://github.com/fokkezb/nl.fokkezb.drawer) widget.

This should be remove because the [nl.fokkezb.drawer](https://github.com/fokkezb/nl.fokkezb.drawer) widget explicitly uses the [Ti.DrawerLayout](https://github.com/manumaticx/Ti.DrawerLayout) module for the Android platform instead of the NappDrawer's Android version. I wonder why.

If you accept pull request, I will send you one.

Thanks for the great work.

**Comment by hansemannn** [comment]
Fixed as part of https://github.com/viezel/NappDrawer/commit/11b763d368b1e6186a1db77d46829adfe1c1abe8
