### ISSUE TITLE
Not supported by Titanium 5.5.0.GA

### ISSUE THREAD

**Issue by carlomilanesi** [viezel/NappDrawer#197]
After having installed the zip file in Titanium, and having added the line <module platform="iphone">dk.napp.drawer</module> in tiapp.xml, in the Modules list of the TiApp Editor there is an exclamation mark icon with the tooltip "The 'dk.napp.drawer' module is not supported by Titanium SKD 5.5.0.GA". The module name is dimmed. The same happens for 5.4.0.GA and for 5.3.1.GA. I tried also to remove platform="iphone". And how can I enable Android support?

**Comment by rwuttke** [comment]
I am running this on 5.4.0.GA no problems for iPhone and Android.

By enabling Android support, do you mean for Appcelerator?

If so, on the Dashboard page, there should be 4 buttons on the top, one for Android and it may say it is not installed, click this and follow the wizard.

**Comment by carlomilanesi** [comment]
Using Appcelerator Studio, I get the following message:
![issue1](https://cloud.githubusercontent.com/assets/8809112/18918078/ee87fe42-8599-11e6-8699-f07c497fa14c.png)

**Comment by caspahouzer** [comment]
Did you try to build it? 5.5.0GA works for me with this module 

- Sebastian 

Sent from my iPhone

**Comment by Geek-Fish** [comment]
Have you guys actually tried this on a device running a version of Android 6 or above? It instantly crashes, but works fine in the emulator. Just an FYI before you start deploying these apps for public release.

**Comment by mmaliki** [comment]
I'm having the same problem described here by Geek-Fish
