### ISSUE TITLE
[iOS7] Crashes when using Alloy and setLeftWindow

### ISSUE THREAD

**Issue by atypical** [viezel/NappDrawer#20]
Hi there,

First - the module is a gem, thank you.

The issue I'm running into is using the module in iOS7 and with Alloy.

This code works brilliantly in iOS6, but not in 7:

drawer.setLeftWindow(Alloy.createController("leftDrawer").getView());

Basically, I start the whole thing in my alloy.js and set default views. After a user logs in via the app, I need to rewrite the left drawer to show a nav. Works perfectly in iOS6, but in iOS7 the simulator just fails when I get to the point of setting the left drawer.

The console tells me almost nothing and in Xcode, all it points to is the setLeftWindow method.

Any ideas? What info can I provide to help?

Thank you!
//MD

**Comment by chrisribe** [comment]
One solution is to set holder windows on init and simple add and remove the views from them. Workaround but....
