### ISSUE TITLE
Not working with SDK 6.3.0

### ISSUE THREAD

**Issue by MarcoDuff** [viezel/NappDrawer#207]
On Titanium 6.3.0.GA module goes in runtime error:

11-21 15:07:08.521   688   688 D AndroidRuntime: Shutting down VM
11-21 15:07:08.523   688   688 E AndroidRuntime: FATAL EXCEPTION: main
11-21 15:07:08.523   688   688 E AndroidRuntime: Process: it.aci.informatica.useyourcard.merchant, PID: 688
11-21 15:07:08.523   688   688 E AndroidRuntime: java.lang.ClassCastException: org.appcelerator.kroll.common.TiMessenger$2 cannot be cast to java.lang.Boolean
11-21 15:07:08.523   688   688 E AndroidRuntime: 	at dk.napp.drawer.DrawerProxy.handleMessage(DrawerProxy.java:68)
11-21 15:07:08.523   688   688 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:98)
11-21 15:07:08.523   688   688 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
11-21 15:07:08.523   688   688 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6165)
11-21 15:07:08.523   688   688 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-21 15:07:08.523   688   688 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
11-21 15:07:08.523   688   688 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)

**Comment by Marchief** [comment]
Experienced this today as well. After a lot of debugging it seems, Appcelerator has added a new setting to the TiApp.XML
 <property name="run-on-main-thread" type="bool">true</property>
Put that with the other properties before <ios> declaration and it should fix it.

**Comment by MarcoDuff** [comment]
Hi @Marchief 
I sorry, but i don't understand. Which setting i must add to tiapp.xml?

**Comment by trkfabi** [comment]
I have this module working with 6.3.0.GA on both iOS and Android.

**Comment by Marchief** [comment]
Sorry, forgot markdown, updated my comment.
@trkfabi it works with new projects as the new property is added by default, however, it is not for legacy projects that are upgrading to 6.0 +

**Comment by MarcoDuff** [comment]
@Marchief It works!

Thank you!
