### ISSUE TITLE
Latest Titanium SDK not support 

### ISSUE THREAD

**Issue by Hemantsolanki103** [viezel/NappDrawer#209]
Hi Team,

NappDrawer not supported for titanium SDK >7.x.x. Please provide latest module for this.

Thanks & Regards,
Hemant Solanki

**Comment by viezel** [comment]
@Hemantsolanki103 please create a PR with the fix for this.

**Comment by SquirrelMobile** [comment]
[dk.napp.drawer-android-2.0.2.zip](https://github.com/viezel/NappDrawer/files/1603550/dk.napp.drawer-android-2.0.2.zip)

For those who looking for the module that works with SDK Titanium > 7.0.0

**Comment by Hemantsolanki103** [comment]
@SquirrelMobile , Thank you so much for your reply and resolved my query.

**Comment by SquirrelMobile** [comment]
@viezel i've just did it here https://github.com/viezel/NappDrawer/pull/210.

@Hemantsolanki103, you're welcome. If you want update a Android module yourself, you can follow with tutorial : https://wiki.appcelerator.org/display/guides2/Android+Module+Upgrade+Guide
Just run `appc run p android --build-only` on the module folder (you must have the Android NDK before and not have space in your module path).

**Comment by Hemantsolanki103** [comment]
@SquirrelMobile , this is great tutorial and thank you for your quick reply.

**Comment by hansemannn** [comment]
@viezel Can you close this issue? I am trying to work myself through open (and relevant) iOS issues.
