### ISSUE TITLE
iOS - setLeftWindow(false) throws error using Titanium 7.1.0 GA

### ISSUE THREAD

**Issue by ulissesrsilva** [viezel/NappDrawer#218]
Hey everyone!

I've just updated SDK version from 6.3.0 to 7.1.0 and setLeftWindow/setRightWindow methods stop working when I pass `false` as a parameter to disable the window. It was working just fine in 6.3.0.
NappDrawer version is 2.1.0

My code:
var centerWindow = Ti.UI.createWindow({backgroundColor: "#000"});
var rightWindow = Ti.UI.createWindow({backgroundColor: "#999"});
var nappWindow = NappDrawerModule.createDrawer({
	centerWindow : centerWindow,
	rightWindow : rightWindow,
	closeDrawerGestureMode : NappDrawerModule.CLOSE_MODE_ALL,
	openDrawerGestureMode : NappDrawerModule.OPEN_MODE_ALL,
	rightDrawerWidth : 280
});
nappWindow.setLeftWindow(false);

Console error:
![captura de tela 2018-03-20 as 22 36 27](https://user-images.githubusercontent.com/8303691/37691247-302ff942-2c8f-11e8-924d-c4f8e6717bdc.png)
![captura de tela 2018-03-20 as 22 36 15](https://user-images.githubusercontent.com/8303691/37691253-37726528-2c8f-11e8-8ad1-5f4cdc16e5cc.png)

How can I fix this?

**Comment by hansemannn** [comment]
You cannot pass a boolean to a method that expects a window instance. If you want to show/hide it, use the related methods for that please.
