### ISSUE TITLE
Bug: centerWindow doesn't fire open or focus events on iOS

### ISSUE THREAD

**Issue by FokkeZB** [viezel/NappDrawer#37]

**Comment by bxgrant** [comment]
Any ideas on this one?  I'm toast without being able to tell when the user comes back to the home screen.

**Comment by pablotango** [comment]
any news about this? there is no way to handle focus on center window?

**Comment by abada** [comment]
Any news about this issue ?

**Comment by chmiiller** [comment]
Any news on this? I've noticed that it does fire a `open` event but not `focus` =/

**Comment by chmiiller** [comment]
Guys, please someone has somehow a path to give me so I can try to implement this by myself on the module? I was reading about viewDidAppear and how it is implemented on Titanium windows but I have no idea how to apply that on this module. And I really need this...please help!

**Comment by hansemannn** [comment]
Fixed by https://github.com/viezel/NappDrawer/pull/211
