### ISSUE TITLE
Crash when Google Map is added

### ISSUE THREAD

**Issue by shufaz** [viezel/NappDrawer#50]
App always crashes when I added map to the centerView. There was no problem with the map itself since I've tested it without NappDrawer. Anyone had this figured out - or NappDrawer doesn't support map?

Building with Titanium SDK 3.2, on android, with Google Maps v2 (2.1.3 version module)

Thanks in advance for any help.

**Comment by marconealberto** [comment]
this is still happening, did anyone find a workaround?

**Comment by Max87ZA** [comment]
I have this problem for a long time and finally @bitfabrikken solution works for me. Important thing is, that you have to add mapView after drawer opens.
