### ISSUE TITLE
drawer.close() memory leak

### ISSUE THREAD

**Issue by jpntex** [viezel/NappDrawer#86]
When i call drawer.close() all the windows created by the module are kept in memory. Is there a way to destroy those windows?

**Comment by mpociot** [comment]
As this is quite an important issue, I took some more time to look into it..

I think we need to call `windowDidClose` on the proxy objects, when closing the drawer.
See: 

https://github.com/appcelerator/titanium_mobile/blob/master/iphone/Classes/TiUIiPadSplitWindowProxy.m#L49

**Comment by mpociot** [comment]
The `MMDrawerCenterContainerView` is also in memory...maybe that's a hint.

![image](https://cloud.githubusercontent.com/assets/804684/5809528/cb1ac95e-a039-11e4-9301-49396c69934d.png)

**Comment by omorandi** [comment]
I had a look at the issue and posted https://github.com/viezel/NappDrawer/pull/140. I think the major issue was given by not compiling the MMDrawer files with ARC
