### ISSUE TITLE
App crashes when using drawer.close() IOS 7.1

### ISSUE THREAD

**Issue by wehttam0** [viezel/NappDrawer#92]
When using the .close() on the drawer object the drawer is cleaned up nicely and transitions to another window. The problem is after five seconds or so, clicking anywhere on the screen causes the app to crash. This seems similar to issue#79/85 which is now closed. Here is a snippet from the crashlog. 

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libobjc.A.dylib                     0x03fc20b2 objc_msgSend + 14
1   MyApp                           0x0007f16d -[TiViewProxy layoutChildrenIfNeeded] + 157 (TiViewProxy.m:2268)
2   MyApp                           0x00209557 +[TiLayoutQueue layoutProxy:] + 87 (TiLayoutQueue.m:80)
3   MyApp                           0x00209329 performLayoutRefresh + 553 (TiLayoutQueue.m:47)
4   CoreFoundation                      0x04b25ac6 **CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION** + 22
5   CoreFoundation                      0x04b254ad __CFRunLoopDoTimer + 1181
6   CoreFoundation                      0x04b0d538 __CFRunLoopRun + 1816
7   CoreFoundation                      0x04b0c9d3 CFRunLoopRunSpecific + 467
8   CoreFoundation                      0x04b0c7eb CFRunLoopRunInMode + 123
9   GraphicsServices                    0x0512f5ee GSEventRunModal + 192
10  GraphicsServices                    0x0512f42b GSEventRun + 104
11  UIKit                               0x0163af9b UIApplicationMain + 1225
12  MyApp                           0x00005f48 main + 456 (main.m:36)
13  libdyld.dylib                       0x0561e701 start + 1

**Comment by hansemannn** [comment]
Not an issue anymore.
